AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GenAI Lecture Assistant Lambdas

Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.genai.lambda.handler.UploadLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 1024
      Timeout: 30
      Policies:
        - AmazonS3FullAccess
        - AmazonTranscribeFullAccess
        - AWSLambdaBasicExecutionRole
